name: Build sencondKill

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.events.head_commit.message,'ci skip')"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          # architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build JavaSE Tutorial
        run: mvn clean package -DskipTests=true

      - name: Push Image
        run: |
          image=secondKill:latest
          docker build -f Dockerfile  -t ${image} .
          docker login --username=lianshun1000 --password=${{ secrets.ALI_DOCKER_REGISTRY_PASSWORD }} registry.cn-shanghai.aliyuncs.com
          docker tag $image registry.cn-shanghai.aliyuncs.com/lianshun/$image
          docker push registry.cn-shanghai.aliyuncs.com/lianshun/$image
          echo "image:" ${image}